### ISSUE TITLE
Update the Prevalence filter input to have type = number

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#121]

**Comment by jwildfire** [comment]
## Test notes

Confirm that you can no longer type characters in the prevalence input, and that the up and down buttons work as expected.

**Comment by danedexF5** [comment]
@jwildfire I'm able to type both letters and numbers in that field. Letters just display a red box and don't change the results. Numbers do change the results.

**Comment by jwildfire** [comment]
I think that is fine, @danedexF5. Guessing that different browsers are handling the input slightly differently.

**Comment by samussiah** [comment]
Captured in #130 , fixed in the latest commit to v3.3.0-dev: 858c2cc672eb9a2c704627e1d03e959ccc4027e2

**Comment by emmorris** [comment]
Confirmed that the wider field allows the full two digit number to display now,  Letters are still not accepted, so the original functionality remained intact.
